// <auto-generated />
using System;
using Flora.Messaging.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flora.Messaging.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20260421195851_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flora_core")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flora.Messaging.Domain.UserE2EKey", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<string>("PublicKeyBase64")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key_base64");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserUuid")
                        .HasName("pk_user_e2e_keys");

                    b.ToTable("user_e2e_keys", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserMessage", b =>
                {
                    b.Property<Guid>("MessageUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EncryptedForReceiver")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_for_receiver");

                    b.Property<string>("EncryptedForSender")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_for_sender");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<Guid>("ReceiverUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_uuid");

                    b.Property<Guid>("SenderUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_uuid");

                    b.HasKey("MessageUuid")
                        .HasName("pk_user_messages");

                    b.HasIndex("ReceiverUserUuid")
                        .HasDatabaseName("ix_user_messages_receiver_user_uuid");

                    b.HasIndex("SenderUserUuid")
                        .HasDatabaseName("ix_user_messages_sender_user_uuid");

                    b.HasIndex("SenderUserUuid", "ReceiverUserUuid")
                        .HasDatabaseName("ix_user_messages_sender_receiver");

                    b.ToTable("user_messages", "flora_core");
                });
#pragma warning restore 612, 618
        }
    }
}
