// <auto-generated />
using System;
using Flora.Messaging.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flora.Messaging.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20260609200549_AddUserMessageVideoAssets")]
    partial class AddUserMessageVideoAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flora_core")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flora.Messaging.Domain.KeyEpochPublicIdentity", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<Guid>("KeyEpochId")
                        .HasColumnType("uuid")
                        .HasColumnName("key_epoch_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EpochAccountIdentityPublicKeyBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("epoch_account_identity_public_key_base64url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserUuid", "KeyEpochId")
                        .HasName("pk_key_epoch_public_identities");

                    b.ToTable("key_epoch_public_identities", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserDeviceKey", b =>
                {
                    b.Property<Guid>("DeviceUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_uuid");

                    b.Property<string>("AgreementPublicKeyBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agreement_public_key_base64url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("KeyEpochId")
                        .HasColumnType("uuid")
                        .HasColumnName("key_epoch_id");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SignedByEpochAccountIdentityBase64Url")
                        .HasColumnType("text")
                        .HasColumnName("signed_by_epoch_account_identity_base64url");

                    b.Property<string>("SigningPublicKeyBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signing_public_key_base64url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.HasKey("DeviceUuid")
                        .HasName("pk_user_device_keys");

                    b.HasIndex("UserUuid", "KeyEpochId", "CreatedAt")
                        .HasDatabaseName("ix_user_device_keys_user_epoch_created");

                    b.HasIndex("UserUuid", "KeyEpochId", "Status")
                        .HasDatabaseName("ix_user_device_keys_user_epoch_status");

                    b.ToTable("user_device_keys", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserE2EAccountState", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Freeze")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("freeze");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserUuid")
                        .HasName("pk_user_e2e_account_states");

                    b.ToTable("user_e2e_account_states", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserE2EIdempotencyRecord", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestBodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_body_hash");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.HasKey("IdempotencyKey")
                        .HasName("pk_user_e2e_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_e2e_idempotency_records_expires_at");

                    b.HasIndex("UserUuid", "Operation", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_user_e2e_idempotency_records_user_operation_created");

                    b.ToTable("user_e2e_idempotency_records", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserE2EKey", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<Guid?>("DeviceUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("device_uuid");

                    b.Property<string>("PublicKeyBase64")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key_base64");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserUuid")
                        .HasName("pk_user_e2e_keys");

                    b.HasIndex("DeviceUuid")
                        .IsUnique()
                        .HasDatabaseName("ux_user_e2e_keys_device_uuid")
                        .HasFilter("device_uuid IS NOT NULL");

                    b.ToTable("user_e2e_keys", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserE2EKeyBackup", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<string>("AeadName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aead_name");

                    b.Property<string>("AeadNonceBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aead_nonce_base64url");

                    b.Property<Guid>("BackupKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("backup_key_id");

                    b.Property<int>("BackupRevision")
                        .HasColumnType("integer")
                        .HasColumnName("backup_revision");

                    b.Property<string>("CiphertextBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ciphertext_base64url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EpochSetHashBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("epoch_set_hash_base64url");

                    b.Property<int>("EpochSetRevision")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_set_revision");

                    b.Property<int>("KdfIterations")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_iterations");

                    b.Property<int>("KdfMemoryKiB")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_memory_kib");

                    b.Property<string>("KdfName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kdf_name");

                    b.Property<int>("KdfParallelism")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_parallelism");

                    b.Property<string>("KdfSaltBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kdf_salt_base64url");

                    b.Property<Guid>("PrimaryKeyEpochId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_key_epoch_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("UserUuid")
                        .HasName("pk_user_e2e_key_backups");

                    b.ToTable("user_e2e_key_backups", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserE2ERecoveryBackup", b =>
                {
                    b.Property<Guid>("RecoveryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_key_id");

                    b.Property<string>("AeadName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aead_name");

                    b.Property<string>("AeadNonceBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aead_nonce_base64url");

                    b.Property<string>("CiphertextBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ciphertext_base64url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EpochSetHashBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("epoch_set_hash_base64url");

                    b.Property<int>("EpochSetRevision")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_set_revision");

                    b.Property<int>("KdfIterations")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_iterations");

                    b.Property<int>("KdfMemoryKiB")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_memory_kib");

                    b.Property<string>("KdfName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kdf_name");

                    b.Property<int>("KdfParallelism")
                        .HasColumnType("integer")
                        .HasColumnName("kdf_parallelism");

                    b.Property<string>("KdfSaltBase64Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kdf_salt_base64url");

                    b.Property<Guid>("PrimaryKeyEpochId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_key_epoch_id");

                    b.Property<int>("RecoveryRevision")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_revision");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("WordlistId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wordlist_id");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer")
                        .HasColumnName("words_count");

                    b.HasKey("RecoveryKeyId")
                        .HasName("pk_user_e2e_recovery_backups");

                    b.HasIndex("UserUuid", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_user_e2e_recovery_backups_user_created");

                    b.HasIndex("UserUuid", "RecoveryKeyId")
                        .HasDatabaseName("ix_user_e2e_recovery_backups_user_recovery_key");

                    b.ToTable("user_e2e_recovery_backups", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserE2EUnlockChallenge", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<string>("CanonicalPayloadPreview")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("canonical_payload_preview");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<Guid>("ResetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("reset_request_id");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.HasKey("ChallengeId")
                        .HasName("pk_user_e2e_unlock_challenges");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_e2e_unlock_challenges_expires_at");

                    b.HasIndex("UserUuid", "ChallengeId")
                        .HasDatabaseName("ix_user_e2e_unlock_challenges_user_challenge");

                    b.HasIndex("UserUuid", "ResetRequestId")
                        .HasDatabaseName("ix_user_e2e_unlock_challenges_user_reset");

                    b.HasIndex("UserUuid", "IsUsed", "ExpiresAt")
                        .HasDatabaseName("ix_user_e2e_unlock_challenges_user_active");

                    b.ToTable("user_e2e_unlock_challenges", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserMessage", b =>
                {
                    b.Property<Guid>("MessageUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EncryptedForReceiver")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_for_receiver");

                    b.Property<string>("EncryptedForSender")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_for_sender");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<Guid>("ReceiverUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_uuid");

                    b.Property<Guid>("SenderUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_uuid");

                    b.HasKey("MessageUuid")
                        .HasName("pk_user_messages");

                    b.HasIndex("ReceiverUserUuid", "SenderUserUuid")
                        .HasDatabaseName("ix_user_messages_unread_peer")
                        .HasFilter("is_read = false");

                    b.HasIndex("ReceiverUserUuid", "CreatedAt", "MessageUuid")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_user_messages_receiver_timeline");

                    b.HasIndex("SenderUserUuid", "CreatedAt", "MessageUuid")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_user_messages_sender_timeline");

                    b.HasIndex("ReceiverUserUuid", "SenderUserUuid", "CreatedAt", "MessageUuid")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("ix_user_messages_conversation_cursor_rev");

                    b.HasIndex("SenderUserUuid", "ReceiverUserUuid", "CreatedAt", "MessageUuid")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("ix_user_messages_conversation_cursor");

                    b.ToTable("user_messages", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserMessageImageAsset", b =>
                {
                    b.Property<Guid>("ImageAssetUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("image_asset_uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("EncryptedBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_bytes");

                    b.Property<Guid?>("MessageUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("message_uuid");

                    b.Property<Guid>("ReceiverUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_uuid");

                    b.Property<Guid>("SenderUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_uuid");

                    b.HasKey("ImageAssetUuid")
                        .HasName("pk_user_message_image_assets");

                    b.HasIndex("MessageUuid")
                        .HasDatabaseName("ix_user_message_image_assets_message_uuid");

                    b.HasIndex("ReceiverUserUuid")
                        .HasDatabaseName("ix_user_message_image_assets_receiver_user_uuid");

                    b.HasIndex("SenderUserUuid")
                        .HasDatabaseName("ix_user_message_image_assets_sender_user_uuid");

                    b.HasIndex("SenderUserUuid", "ReceiverUserUuid", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_user_message_image_assets_peer_created");

                    b.ToTable("user_message_image_assets", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserMessageVideoAsset", b =>
                {
                    b.Property<Guid>("VideoAssetUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<byte[]>("EncryptedBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_bytes");

                    b.Property<Guid?>("MessageUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("message_uuid");

                    b.Property<Guid>("ReceiverUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_uuid");

                    b.Property<Guid>("SenderUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_uuid");

                    b.HasKey("VideoAssetUuid")
                        .HasName("pk_user_message_video_assets");

                    b.HasIndex("MessageUuid")
                        .HasDatabaseName("ix_user_message_video_assets_message_uuid");

                    b.HasIndex("ReceiverUserUuid")
                        .HasDatabaseName("ix_user_message_video_assets_receiver_user_uuid");

                    b.HasIndex("SenderUserUuid")
                        .HasDatabaseName("ix_user_message_video_assets_sender_user_uuid");

                    b.HasIndex("SenderUserUuid", "ReceiverUserUuid", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_user_message_video_assets_peer_created");

                    b.ToTable("user_message_video_assets", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserMessageVoiceAsset", b =>
                {
                    b.Property<Guid>("VoiceAssetUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("voice_asset_uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<byte[]>("EncryptedBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_bytes");

                    b.Property<Guid?>("MessageUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("message_uuid");

                    b.Property<Guid>("ReceiverUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_uuid");

                    b.Property<Guid>("SenderUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_uuid");

                    b.HasKey("VoiceAssetUuid")
                        .HasName("pk_user_message_voice_assets");

                    b.HasIndex("MessageUuid")
                        .HasDatabaseName("ix_user_message_voice_assets_message_uuid");

                    b.HasIndex("ReceiverUserUuid")
                        .HasDatabaseName("ix_user_message_voice_assets_receiver_user_uuid");

                    b.HasIndex("SenderUserUuid")
                        .HasDatabaseName("ix_user_message_voice_assets_sender_user_uuid");

                    b.HasIndex("SenderUserUuid", "ReceiverUserUuid", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_user_message_voice_assets_peer_created");

                    b.ToTable("user_message_voice_assets", "flora_core");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserMessageImageAsset", b =>
                {
                    b.HasOne("Flora.Messaging.Domain.UserMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageUuid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_message_image_assets_message");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserMessageVideoAsset", b =>
                {
                    b.HasOne("Flora.Messaging.Domain.UserMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageUuid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_message_video_assets_message");
                });

            modelBuilder.Entity("Flora.Messaging.Domain.UserMessageVoiceAsset", b =>
                {
                    b.HasOne("Flora.Messaging.Domain.UserMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageUuid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_message_voice_assets_message");
                });
#pragma warning restore 612, 618
        }
    }
}
