// <auto-generated />
using System;
using Flora.Users.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flora.Users.Infrastructure.Data.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260608153239_AddUserPrivacyBlocksAndPresence")]
    partial class AddUserPrivacyBlocksAndPresence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flora_core")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flora.Users.Domain.UserAvatar", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_user_avatars");

                    b.ToTable("user_avatars", "flora_core");
                });

            modelBuilder.Entity("Flora.Users.Domain.UserBlock", b =>
                {
                    b.Property<Guid>("OwnerUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_uuid");

                    b.Property<Guid>("BlockedUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_user_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OwnerUserUuid", "BlockedUserUuid")
                        .HasName("pk_user_blocks");

                    b.HasIndex("BlockedUserUuid")
                        .HasDatabaseName("ix_user_blocks_blocked_user_uuid");

                    b.ToTable("user_blocks", "flora_core");
                });

            modelBuilder.Entity("Flora.Users.Domain.UserFollower", b =>
                {
                    b.Property<Guid>("FollowerUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_user_uuid");

                    b.Property<Guid>("FollowingUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("following_user_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FollowerUserUuid", "FollowingUserUuid")
                        .HasName("pk_user_followers");

                    b.HasIndex("FollowingUserUuid")
                        .HasDatabaseName("ix_user_followers_following_user_uuid");

                    b.ToTable("user_followers", "flora_core");
                });

            modelBuilder.Entity("Flora.Users.Domain.UserPresence", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserUuid")
                        .HasName("pk_user_presence");

                    b.ToTable("user_presence", "flora_core");
                });

            modelBuilder.Entity("Flora.Users.Domain.UserPrivacySettings", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<int>("CommentsFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("comments_from");

                    b.Property<int>("FriendsVisibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("friends_visibility");

                    b.Property<int>("LikesVisibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("likes_visibility");

                    b.Property<int>("MessagesFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("messages_from");

                    b.Property<int>("OnlineFriends")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("online_friends");

                    b.Property<int>("OnlineStrangers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("online_strangers");

                    b.Property<int>("PostsVisibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("posts_visibility");

                    b.Property<int>("RepostsVisibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reposts_visibility");

                    b.Property<int>("SubscriptionsVisibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("subscriptions_visibility");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserUuid")
                        .HasName("pk_user_privacy_settings");

                    b.ToTable("user_privacy_settings", "flora_core");
                });

            modelBuilder.Entity("Flora.Users.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<Guid?>("AvatarUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("display_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Status")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserUuid")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", "flora_core");
                });
#pragma warning restore 612, 618
        }
    }
}
