import { StyleSheet } from "react-native";
import { floraColors, floraSpacing } from "@/lib/theme";

const DIVIDER = "rgba(250, 250, 250, 0.08)";
const INPUT_BORDER = "rgba(250, 250, 250, 0.15)";

/** Визуальный язык вкладки настроек — паритет с Apps/Web settings.module.css. */
export const settingsUi = StyleSheet.create({
  tabBody: {
    gap: floraSpacing.grid * 2,
    paddingTop: floraSpacing.grid,
  },
  section: {
    gap: floraSpacing.grid * 2,
  },
  sectionTitle: {
    color: floraColors.whiteTemplate,
    fontSize: 18,
    fontWeight: "300",
    letterSpacing: 0.54,
    lineHeight: floraSpacing.grid * 2,
    paddingBottom: floraSpacing.grid - 1,
    borderBottomColor: DIVIDER,
    borderBottomWidth: 1,
  },
  fieldsStack: {
    gap: floraSpacing.grid,
  },
  fieldGroup: {
    gap: 0,
  },
  fieldLabel: {
    color: floraColors.gray,
    fontSize: 13,
    fontWeight: "300",
    letterSpacing: 0.45,
    height: floraSpacing.grid * 2,
    lineHeight: floraSpacing.grid + floraSpacing.gridFine,
    paddingBottom: floraSpacing.gridFine,
    paddingLeft: 2,
    textAlignVertical: "bottom",
    includeFontPadding: false,
  },
  input: {
    backgroundColor: "transparent",
    borderColor: INPUT_BORDER,
    borderWidth: 1,
    borderRadius: 10,
    color: floraColors.whiteTemplate,
    paddingHorizontal: floraSpacing.grid,
    height: floraSpacing.grid * 3,
    fontSize: 15,
    fontWeight: "300",
  },
  feedbackError: {
    color: "#f6a8a8",
    fontSize: 12,
    fontWeight: "300",
    lineHeight: 17,
  },
  feedbackSuccess: {
    color: floraColors.greenLight,
    fontSize: 12,
    fontWeight: "300",
    lineHeight: 17,
  },
  avatarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: floraSpacing.grid * 2,
  },
  avatarActions: {
    flex: 1,
    gap: floraSpacing.gridFine,
    justifyContent: "center",
    minWidth: 0,
  },
  textAction: {
    alignSelf: "flex-start",
    justifyContent: "center",
    minHeight: floraSpacing.grid * 2 + floraSpacing.gridFine * 2,
    paddingVertical: floraSpacing.gridFine,
    paddingHorizontal: 0,
  },
  textActionPrimary: {
    color: floraColors.greenLight,
    fontSize: 15,
    fontWeight: "300",
    letterSpacing: 0.45,
  },
  textActionMuted: {
    color: floraColors.gray,
    fontSize: 15,
    fontWeight: "300",
    letterSpacing: 0.45,
  },
  textActionDisabled: {
    opacity: 0.4,
  },
  primaryButton: {
    alignSelf: "flex-start",
    minHeight: floraSpacing.grid * 3,
    minWidth: 120,
    paddingHorizontal: floraSpacing.grid * 2,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(164, 209, 138, 0.12)",
  },
  primaryButtonText: {
    color: floraColors.greenLight,
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.42,
  },
  listCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: floraSpacing.grid * 2,
    paddingVertical: floraSpacing.grid,
    paddingHorizontal: floraSpacing.grid * 1.5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DIVIDER,
    backgroundColor: "rgba(250, 250, 250, 0.02)",
    minHeight: floraSpacing.grid * 5,
  },
  listCardInfo: {
    flex: 1,
    gap: floraSpacing.gridFine,
    minWidth: 0,
  },
  listCardTitle: {
    color: floraColors.whiteTemplate,
    fontSize: 15,
    fontWeight: "400",
    lineHeight: floraSpacing.grid,
  },
  listCardDesc: {
    color: floraColors.gray,
    fontSize: 13,
    fontWeight: "300",
    lineHeight: floraSpacing.grid,
  },
  dangerButton: {
    flexShrink: 0,
    height: floraSpacing.grid * 3,
    minWidth: floraSpacing.grid * 8,
    paddingHorizontal: floraSpacing.grid * 2,
    borderRadius: floraSpacing.gridFine * 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(246, 168, 168, 0.15)",
  },
  dangerButtonText: {
    color: "#f6a8a8",
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.42,
  },
  dangerOutlineButton: {
    alignSelf: "stretch",
    minHeight: floraSpacing.grid * 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(246, 168, 168, 0.55)",
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: floraSpacing.grid * 2,
  },
  dangerOutlineButtonText: {
    color: "#f6a8a8",
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.42,
  },
  pressed: {
    opacity: 0.72,
  },
  inlineFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: floraSpacing.gridFine * 2,
  },
  inlineFieldGrow: {
    flex: 1,
    minWidth: 0,
  },
  ghostButton: {
    minHeight: floraSpacing.grid * 3,
    paddingHorizontal: floraSpacing.grid,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  ghostButtonText: {
    color: floraColors.gray,
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.42,
  },
  softPrimaryButton: {
    flexShrink: 0,
    height: floraSpacing.grid * 3,
    minWidth: floraSpacing.grid * 8,
    paddingHorizontal: floraSpacing.grid * 2,
    borderRadius: floraSpacing.gridFine * 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(164, 209, 138, 0.12)",
  },
  softPrimaryButtonText: {
    color: floraColors.greenLight,
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.42,
  },
  softMutedButton: {
    flexShrink: 0,
    height: floraSpacing.grid * 3,
    minWidth: floraSpacing.grid * 6,
    paddingHorizontal: floraSpacing.grid * 2,
    borderRadius: floraSpacing.gridFine * 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(250, 250, 250, 0.06)",
  },
  softMutedButtonText: {
    color: floraColors.gray,
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.42,
  },
  badge: {
    marginLeft: floraSpacing.gridFine,
    paddingHorizontal: floraSpacing.gridFine * 2,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(164, 209, 138, 0.15)",
  },
  badgeText: {
    color: floraColors.greenLight,
    fontSize: 11,
    fontWeight: "400",
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    flexWrap: "wrap",
    minHeight: floraSpacing.grid * 2,
    paddingBottom: floraSpacing.gridFine,
  },
  formActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: floraSpacing.grid,
    alignItems: "center",
    marginTop: floraSpacing.gridFine,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: floraSpacing.grid,
    paddingBottom: floraSpacing.grid - 1,
    borderBottomColor: DIVIDER,
    borderBottomWidth: 1,
  },
  sectionHeaderTitle: {
    flex: 1,
    minWidth: 0,
    color: floraColors.whiteTemplate,
    fontSize: 18,
    fontWeight: "300",
    letterSpacing: 0.54,
    lineHeight: floraSpacing.grid * 2,
  },
  /** Readonly value + «Изменить» — без disabled-инпута. */
  valueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: floraSpacing.grid,
    minHeight: floraSpacing.grid * 3,
  },
  valueText: {
    flex: 1,
    minWidth: 0,
    color: floraColors.whiteTemplate,
    fontSize: 15,
    fontWeight: "300",
    letterSpacing: 0.45,
  },
  valuePlaceholder: {
    color: "rgba(250, 250, 250, 0.3)",
  },
  /** Раскрытая форма смены email/пароля. */
  nestedForm: {
    gap: floraSpacing.grid,
    padding: floraSpacing.grid,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DIVIDER,
    backgroundColor: "rgba(250, 250, 250, 0.03)",
  },
  labelWithMeta: {
    flexDirection: "row",
    alignItems: "flex-end",
    flexWrap: "wrap",
    gap: floraSpacing.gridFine * 2,
    minHeight: floraSpacing.grid * 2,
    paddingBottom: floraSpacing.gridFine,
    paddingLeft: 2,
  },
  verifiedText: {
    color: "rgba(164, 209, 138, 0.72)",
    fontSize: 12,
    fontWeight: "300",
    letterSpacing: 0.3,
    paddingBottom: 1,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: floraSpacing.gridFine,
  },
  outlineBadge: {
    paddingHorizontal: floraSpacing.gridFine * 2,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(164, 209, 138, 0.4)",
  },
  outlineBadgeText: {
    color: floraColors.greenLight,
    fontSize: 11,
    fontWeight: "400",
    letterSpacing: 0.2,
  },
  textActionDanger: {
    color: "#f6a8a8",
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.42,
  },
  listCardActionCol: {
    flexShrink: 0,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  confirmCheckRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: floraSpacing.grid,
    paddingVertical: floraSpacing.gridFine,
  },
  confirmCheckBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  confirmCheckBoxOn: {
    borderColor: "rgba(164, 209, 138, 0.55)",
    backgroundColor: "rgba(164, 209, 138, 0.15)",
  },
  confirmCheckLabel: {
    flex: 1,
    color: floraColors.gray,
    fontSize: 13,
    fontWeight: "300",
    lineHeight: 18,
  },
  sectionHint: {
    color: floraColors.gray,
    fontSize: 13,
    fontWeight: "300",
    lineHeight: floraSpacing.grid,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.55)",
    justifyContent: "center",
    paddingHorizontal: floraSpacing.grid * 2,
  },
  modalCard: {
    borderRadius: floraSpacing.grid,
    backgroundColor: floraColors.surfaceElevated,
    borderWidth: 1,
    borderColor: floraColors.border,
    padding: floraSpacing.grid * 2,
    gap: floraSpacing.grid,
    maxHeight: "88%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: floraSpacing.grid,
  },
  modalTitle: {
    flex: 1,
    color: floraColors.whiteTemplate,
    fontSize: 18,
    fontWeight: "300",
    letterSpacing: 0.54,
  },
  modalBody: {
    color: floraColors.gray,
    fontSize: 14,
    fontWeight: "300",
    lineHeight: 20,
  },
  monoBlock: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: DIVIDER,
    backgroundColor: "rgba(250, 250, 250, 0.04)",
    padding: floraSpacing.grid,
    gap: floraSpacing.gridFine,
  },
  monoText: {
    color: floraColors.whiteTemplate,
    fontSize: 14,
    fontWeight: "300",
    lineHeight: 21,
    letterSpacing: 0.4,
  },
  monoHint: {
    color: floraColors.gray,
    fontSize: 12,
    fontWeight: "300",
  },
  quietExpand: {
    gap: floraSpacing.grid,
    paddingTop: floraSpacing.gridFine,
    borderTopWidth: 1,
    borderTopColor: DIVIDER,
    marginTop: floraSpacing.gridFine,
  },
  quietTimeRow: {
    flexDirection: "row",
    gap: floraSpacing.grid,
  },
  quietTimeField: {
    flex: 1,
    minWidth: 0,
    gap: 0,
  },
  matrixWrap: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DIVIDER,
    backgroundColor: "rgba(250, 250, 250, 0.02)",
    overflow: "hidden",
  },
  matrixHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: floraSpacing.grid,
    paddingVertical: floraSpacing.gridFine * 2,
    borderBottomWidth: 1,
    borderBottomColor: DIVIDER,
    gap: floraSpacing.gridFine,
  },
  matrixRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: floraSpacing.grid,
    paddingVertical: floraSpacing.gridFine * 2,
    borderBottomWidth: 1,
    borderBottomColor: DIVIDER,
    gap: floraSpacing.gridFine,
  },
  matrixRowLast: {
    borderBottomWidth: 0,
  },
  matrixEventCol: {
    flex: 1.4,
    minWidth: 0,
  },
  matrixEventText: {
    color: floraColors.whiteTemplate,
    fontSize: 13,
    fontWeight: "300",
    lineHeight: 18,
  },
  matrixChannelCol: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  matrixChannelLabel: {
    color: floraColors.gray,
    fontSize: 11,
    fontWeight: "300",
    textAlign: "center",
    lineHeight: 14,
  },
  matrixCheck: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    alignItems: "center",
    justifyContent: "center",
  },
  matrixCheckOn: {
    borderColor: "rgba(164, 209, 138, 0.55)",
    backgroundColor: "rgba(164, 209, 138, 0.15)",
  },
});
