import { StyleSheet } from "react-native";
import { floraAuthTypography, floraColors } from "@/lib/theme";

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: floraColors.bg,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  inner: {
    width: "100%",
    maxWidth: 380,
    alignSelf: "center",
    gap: 14,
  },
  logoRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "baseline",
    alignSelf: "center",
    width: "100%",
    gap: 12,
    minHeight: 66,
    marginTop: 24,
    marginBottom: 32,
  },
  logoLetter: {
    color: floraColors.greenLight,
    fontSize: floraAuthTypography.sizeLogo,
    fontWeight: floraAuthTypography.light,
    lineHeight: 30,
    letterSpacing: floraAuthTypography.letterLogo,
    includeFontPadding: false,
  },
  logoIdGap: {
    marginLeft: 27,
  },
  formStack: {
    gap: 14,
  },
  fieldBlock: {
    gap: 4,
  },
  fieldRow: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: 11,
    minHeight: 42,
  },
  iconCell: {
    width: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  fieldInputWrap: {
    flex: 1,
    minHeight: 19,
    justifyContent: "center",
    position: "relative",
  },
  fieldInput: {
    color: floraColors.grayLight,
    fontSize: floraAuthTypography.sizeBody,
    fontWeight: floraAuthTypography.light,
    letterSpacing: floraAuthTypography.letterWide,
    paddingVertical: 0,
    paddingBottom: 2,
    paddingRight: 34,
  },
  fieldInputWhite: {
    color: floraColors.whiteTemplate,
  },
  underlineTrack: {
    height: 1,
    backgroundColor: "rgba(143, 143, 143, 0.78)",
    overflow: "hidden",
  },
  underlineActive: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 1,
    backgroundColor: floraColors.greenLight,
  },
  passwordToggle: {
    position: "absolute",
    right: 0,
    top: -2,
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  submit: {
    marginTop: 15,
    height: 52,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: floraColors.gray,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 3,
  },
  submitPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.988 }],
  },
  submitDisabled: {
    opacity: 0.45,
  },
  submitText: {
    color: floraColors.grayLight,
    fontSize: floraAuthTypography.sizeBody,
    fontWeight: floraAuthTypography.light,
    letterSpacing: floraAuthTypography.letterButton,
  },
  submitTextWhite: {
    color: floraColors.whiteTemplate,
  },
  links: {
    marginTop: 15,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 15,
  },
  linkMuted: {
    color: floraColors.gray,
    fontSize: floraAuthTypography.sizeBody,
    fontWeight: floraAuthTypography.light,
    letterSpacing: floraAuthTypography.letterLink,
  },
  linkAccent: {
    color: floraColors.greenLight,
    fontSize: floraAuthTypography.sizeBody,
    fontWeight: floraAuthTypography.light,
    letterSpacing: floraAuthTypography.letterLink,
  },
  backLink: {
    color: floraColors.gray,
    fontSize: 14,
    fontWeight: floraAuthTypography.light,
    letterSpacing: 1.55,
    textAlign: "center",
  },
  error: {
    color: floraColors.gray,
    fontSize: 12,
    fontWeight: floraAuthTypography.light,
    textAlign: "center",
    lineHeight: 17,
  },
  errorToastWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 60,
    alignItems: "center",
    paddingHorizontal: 20,
  },
  errorToast: {
    width: "100%",
    maxWidth: 380,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(143, 143, 143, 0.45)",
    backgroundColor: "rgba(20, 20, 20, 0.96)",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  errorToastText: {
    color: floraColors.grayLight,
    fontSize: 13,
    fontWeight: floraAuthTypography.light,
    textAlign: "center",
    lineHeight: 18,
    letterSpacing: 0.4,
  },
  devHint: {
    color: floraColors.gray,
    fontSize: 12,
    fontWeight: floraAuthTypography.light,
    textAlign: "center",
    lineHeight: 17,
    marginBottom: 8,
  },
  devHintStrong: {
    fontWeight: "600",
    letterSpacing: 0.8,
  },
  busyOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(12, 12, 12, 0.35)",
    zIndex: 50,
  },
  busyDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: floraColors.greenLight,
    borderTopColor: "transparent",
  },
});
