import { StyleSheet } from "react-native";
import { liveGridStyles } from "@/lib/liveGridStyles";
import { floraAuthTypography, floraColors, floraSpacing, kegl, sPx, tracking } from "@/lib/theme";

export const authStyles = liveGridStyles(() => StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: floraColors.bg,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: sPx(20),
    paddingVertical: sPx(28),
  },
  inner: {
    width: "100%",
    maxWidth: sPx(380),
    alignSelf: "center",
    gap: sPx(14),
  },
  logoRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "baseline",
    alignSelf: "center",
    width: "100%",
    gap: sPx(12),
    minHeight: sPx(66),
    marginTop: sPx(24),
    marginBottom: sPx(32),
  },
  logoLetter: {
    color: floraColors.greenLight,
    fontSize: floraAuthTypography.sizeLogo,
    fontWeight: floraAuthTypography.light,
    lineHeight: sPx(30),
    letterSpacing: floraAuthTypography.letterLogo,
    includeFontPadding: false,
  },
  logoIdGap: {
    marginLeft: sPx(27),
  },
  formStack: {
    gap: sPx(14),
  },
  fieldBlock: {
    gap: sPx(4),
  },
  fieldRow: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: sPx(11),
    minHeight: sPx(42),
  },
  iconCell: {
    width: sPx(24),
    alignItems: "center",
    justifyContent: "center",
  },
  fieldInputWrap: {
    flex: 1,
    minHeight: sPx(19),
    justifyContent: "center",
    position: "relative",
  },
  fieldInput: {
    color: floraColors.grayLight,
    fontSize: floraAuthTypography.sizeBody,
    fontWeight: floraAuthTypography.light,
    letterSpacing: floraAuthTypography.letterWide,
    paddingVertical: 0,
    paddingBottom: sPx(2),
    paddingRight: sPx(34),
  },
  fieldInputWhite: {
    color: floraColors.whiteTemplate,
  },
  underlineTrack: {
    height: 1,
    backgroundColor: "rgba(143, 143, 143, 0.78)",
    overflow: "hidden",
  },
  underlineActive: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 1,
    backgroundColor: floraColors.greenLight,
  },
  passwordToggle: {
    position: "absolute",
    right: 0,
    top: -sPx(2),
    width: sPx(34),
    height: sPx(34),
    alignItems: "center",
    justifyContent: "center",
  },
  submit: {
    marginTop: 0,
    height: sPx(52),
    borderRadius: sPx(20),
    borderWidth: 1,
    borderColor: floraColors.gray,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: sPx(3),
  },
  submitPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.988 }],
  },
  submitDisabled: {
    opacity: 0.45,
  },
  submitText: {
    color: floraColors.grayLight,
    fontSize: floraAuthTypography.sizeBody,
    fontWeight: floraAuthTypography.light,
    letterSpacing: floraAuthTypography.letterButton,
  },
  submitTextWhite: {
    color: floraColors.whiteTemplate,
  },
  /** Резерв высоты как у «Забыли пароль?» — одинаковый отступ до кнопки во всех режимах. */
  preSubmitSlot: {
    alignSelf: "stretch",
    height: sPx(34),
    position: "relative",
    marginTop: sPx(2),
  },
  forgotPasswordPseudo: {
    position: "absolute",
    right: sPx(2),
    top: 0,
    zIndex: 2,
  },
  forgotPasswordLink: {
    color: floraColors.gray,
    fontSize: kegl(13),
    fontWeight: floraAuthTypography.light,
    letterSpacing: tracking(0.4),
    lineHeight: sPx(18),
  },
  links: {
    marginTop: floraSpacing.grid,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    gap: floraSpacing.grid,
  },
  linkMuted: {
    color: floraColors.gray,
    fontSize: floraAuthTypography.sizeBody,
    fontWeight: floraAuthTypography.light,
    letterSpacing: floraAuthTypography.letterLink,
  },
  linkAccent: {
    color: floraColors.greenLight,
    fontSize: floraAuthTypography.sizeBody,
    fontWeight: floraAuthTypography.light,
    letterSpacing: floraAuthTypography.letterLink,
  },
  backLink: {
    color: floraColors.gray,
    fontSize: kegl(14),
    fontWeight: floraAuthTypography.light,
    letterSpacing: tracking(1.55),
    textAlign: "center",
  },
  error: {
    color: floraColors.gray,
    fontSize: kegl(12),
    fontWeight: floraAuthTypography.light,
    textAlign: "center",
    lineHeight: sPx(17),
  },
  errorToastWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 60,
    alignItems: "center",
    paddingHorizontal: sPx(20),
  },
  errorToast: {
    width: "100%",
    maxWidth: sPx(380),
    borderRadius: sPx(16),
    borderWidth: 1,
    borderColor: "rgba(143, 143, 143, 0.45)",
    backgroundColor: "rgba(20, 20, 20, 0.96)",
    paddingHorizontal: sPx(16),
    paddingVertical: sPx(12),
  },
  errorToastText: {
    color: floraColors.grayLight,
    fontSize: kegl(13),
    fontWeight: floraAuthTypography.light,
    textAlign: "center",
    lineHeight: sPx(18),
    letterSpacing: tracking(0.4),
  },
  devHint: {
    color: floraColors.gray,
    fontSize: kegl(12),
    fontWeight: floraAuthTypography.light,
    textAlign: "center",
    lineHeight: sPx(17),
    marginBottom: sPx(8),
  },
  devHintStrong: {
    fontWeight: "600",
    letterSpacing: tracking(0.8),
  },
  busyOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(12, 12, 12, 0.35)",
    zIndex: 50,
  },
  busyDot: {
    width: sPx(32),
    height: sPx(32),
    borderRadius: sPx(16),
    borderWidth: sPx(2),
    borderColor: floraColors.greenLight,
    borderTopColor: "transparent",
  },
}));
