// <auto-generated />
using System;
using Flora.Content.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flora.Content.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260607154529_AddPostDrafts")]
    partial class AddPostDrafts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flora_core")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flora.Content.Domain.Community", b =>
                {
                    b.Property<Guid>("CommunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("community_id");

                    b.Property<Guid?>("AvatarUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("CommunityId")
                        .HasName("pk_communities");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_communities_slug");

                    b.ToTable("communities", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.CommunityAvatar", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("community_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.HasKey("Uuid")
                        .HasName("pk_community_avatars");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_community_avatars_community_id");

                    b.ToTable("community_avatars", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostComment", b =>
                {
                    b.Property<Guid>("CommentUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("comment_uuid");

                    b.Property<Guid>("AuthorUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PostUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("post_uuid");

                    b.HasKey("CommentUuid")
                        .HasName("pk_post_comments");

                    b.HasIndex("AuthorUserUuid")
                        .HasDatabaseName("ix_post_comments_author_user_uuid");

                    b.HasIndex("PostUuid")
                        .HasDatabaseName("ix_post_comments_post_uuid");

                    b.ToTable("post_comments", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostDraft", b =>
                {
                    b.Property<Guid>("DraftUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("draft_uuid");

                    b.Property<Guid>("AuthorUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_uuid");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("community_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("DraftUuid")
                        .HasName("pk_post_drafts");

                    b.HasIndex("AuthorUserUuid")
                        .HasDatabaseName("ix_post_drafts_author_user_uuid");

                    b.HasIndex("AuthorUserUuid", "CommunityId")
                        .HasDatabaseName("ix_post_drafts_author_community");

                    b.ToTable("post_drafts", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostImage", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<Guid>("PostUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("post_uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Uuid")
                        .HasName("pk_post_images");

                    b.HasIndex("PostUuid")
                        .HasDatabaseName("ix_post_images_post_uuid");

                    b.ToTable("post_images", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostLike", b =>
                {
                    b.Property<Guid>("PostUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("post_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PostUuid", "UserUuid")
                        .HasName("pk_post_likes");

                    b.HasIndex("PostUuid")
                        .HasDatabaseName("ix_post_likes_post_uuid");

                    b.ToTable("post_likes", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostRepost", b =>
                {
                    b.Property<Guid>("PostUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("post_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PostUuid", "UserUuid")
                        .HasName("pk_post_reposts");

                    b.HasIndex("PostUuid")
                        .HasDatabaseName("ix_post_reposts_post_uuid");

                    b.ToTable("post_reposts", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostView", b =>
                {
                    b.Property<Guid>("PostUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("post_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<DateTime>("ViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PostUuid", "UserUuid")
                        .HasName("pk_post_views");

                    b.HasIndex("PostUuid")
                        .HasDatabaseName("ix_post_views_post_uuid");

                    b.ToTable("post_views", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.UserCommunity", b =>
                {
                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("community_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Member")
                        .HasColumnName("role");

                    b.HasKey("UserUuid", "CommunityId")
                        .HasName("pk_user_communities");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_user_communities_community_id");

                    b.ToTable("user_communities", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.UserPost", b =>
                {
                    b.Property<Guid>("PostUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("post_uuid");

                    b.Property<Guid>("AuthorUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_uuid");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("community_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.HasKey("PostUuid")
                        .HasName("pk_user_posts");

                    b.HasIndex("AuthorUserUuid")
                        .HasDatabaseName("ix_user_posts_author_user_uuid");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_user_posts_community_id");

                    b.ToTable("user_posts", "flora_core");
                });

            modelBuilder.Entity("Flora.Content.Domain.CommunityAvatar", b =>
                {
                    b.HasOne("Flora.Content.Domain.Community", null)
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_avatars_community");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostComment", b =>
                {
                    b.HasOne("Flora.Content.Domain.UserPost", null)
                        .WithMany()
                        .HasForeignKey("PostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_comments_post");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostImage", b =>
                {
                    b.HasOne("Flora.Content.Domain.UserPost", null)
                        .WithMany()
                        .HasForeignKey("PostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_images_post");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostLike", b =>
                {
                    b.HasOne("Flora.Content.Domain.UserPost", null)
                        .WithMany()
                        .HasForeignKey("PostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_likes_post");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostRepost", b =>
                {
                    b.HasOne("Flora.Content.Domain.UserPost", null)
                        .WithMany()
                        .HasForeignKey("PostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_reposts_post");
                });

            modelBuilder.Entity("Flora.Content.Domain.PostView", b =>
                {
                    b.HasOne("Flora.Content.Domain.UserPost", null)
                        .WithMany()
                        .HasForeignKey("PostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_views_post");
                });

            modelBuilder.Entity("Flora.Content.Domain.UserCommunity", b =>
                {
                    b.HasOne("Flora.Content.Domain.Community", null)
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_communities_community");
                });
#pragma warning restore 612, 618
        }
    }
}
