using Flora.Shared;

namespace Flora.Auth.Domain;

/// <summary>
/// Зарезервированные никнеймы (<c>/profile/&lt;username&gt;</c>).
/// Нельзя занимать при регистрации и смене username.
/// </summary>
public static class ReservedUsernames
{
    public const string ReservedMessage =
        "Этот никнейм зарезервирован системой и недоступен для регистрации.";

    private static readonly HashSet<string> Exact = new(StringComparer.OrdinalIgnoreCase)
    {
        // Маршруты Flora и служебные имена
        "own", "new", "create", "edit", "delete", "settings", "feed", "messages", "people",
        "communities", "community", "music", "notifications", "profile", "compose", "login",
        "logout", "signin", "sign_in", "signup", "sign_up", "register", "auth", "oauth",
        "callback", "webhook", "api", "admin", "administrator", "administration", "moderation",
        "moderator", "moderators", "mod", "mods", "staff", "team", "internal", "system", "root",
        "null", "undefined", "true", "false", "me", "self", "user", "users", "public", "private",
        "search", "explore", "discover", "trending", "recommended", "recommendations",
        "subscriptions", "following", "followers", "archive", "archived", "draft", "drafts",
        "post", "posts", "comment", "comments", "message", "channel", "channels", "group",
        "groups", "event", "events", "notification", "help", "support", "about", "contact",
        "terms", "privacy", "policy", "legal", "security", "trust", "safety", "report", "abuse",
        "copyright", "dmca", "status", "health", "ping", "metrics", "debug", "test", "testing",
        "demo", "staging", "production", "prod", "dev", "development", "beta", "alpha",
        "preview", "release", "updates", "blog", "news", "press", "media", "careers", "jobs",
        "billing", "payment", "payments", "invoice", "checkout", "subscribe", "unsubscribe",
        "verify", "verification", "confirm", "confirmation", "reset", "restore", "recover",
        "recovery", "account", "accounts", "password", "passwd", "email", "mail", "inbox",
        "sent", "trash", "spam", "flora", "floras", "flora_s", "flora_net", "flora_official",
        "flora_team", "flora_support", "flora_admin", "flora_security", "official", "verified",
        "bluecheck", "partner", "partners", "ambassador", "brand", "brands", "trademark",
        "www", "app", "web", "mobile", "desktop", "static", "assets", "cdn", "files", "upload",
        "uploads", "download", "downloads", "share", "invite", "invites", "join", "leave",
        "ban", "banned", "suspend", "suspended", "delete_account", "deactivate",
        "support_team", "help_center", "helpdesk", "customer_support", "tech_support",
        "security_team", "trust_and_safety", "abuse_team", "report_abuse", "admin_panel",
        "admin_console", "dashboard_admin", "moderator_team", "official_community",
        "official_page", "verified_community", "customer_service", "service_desk",
        "phishing", "scam", "scams", "fraud", "carding", "darknet", "dark_web", "darkmarket",
        "malware", "ransomware", "exploit", "botnet", "hacker", "hackers", "hacking", "hack",
        "crack", "cracks", "keygen", "warez", "illegal", "contraband", "carder", "carders",
        "stealer", "stealers", "phish", "spoof", "spoofing", "identity_theft",
        "drugs", "narcotics", "cocaine", "heroin", "meth", "fentanyl", "weapon", "weapons",
        "firearms", "gun", "guns", "ammunition", "terrorism", "terrorist", "terrorists",
        "extremism", "extremist", "isis", "isil", "nazism", "nazi", "hitler", "child_abuse",
        "csam", "pedophile", "pedophilia", "trafficking", "human_trafficking",
        "money_laundering", "sanctions", "sanctioned", "organized_crime", "mafia",
        "porn", "pornhub", "xxx", "sex_trade", "escort_service", "prostitution",
        "meta", "instagram", "telegram", "whatsapp", "vk", "vkontakte", "youtube", "tiktok",
        "twitter", "x_com", "facebook", "google", "apple", "microsoft", "amazon", "netflix",
        "spotify", "paypal", "visa", "mastercard", "stripe", "coinbase", "binance",
        "gosuslugi", "nalog", "fns", "mvd", "fsb", "rosgvardia", "kremlin", "government",
        "gov_ru", "govru", "minjust", "roskomnadzor", "cbr", "central_bank", "sberbank",
        "tinkoff", "vtb", "alfabank", "raiffeisen", "rosbank",
        "fbi", "cia", "nsa", "dhs", "dod", "dea", "atf", "ice", "cbp", "tsa", "uscis",
        "irs", "treasury", "us_treasury", "state_department", "whitehouse", "white_house",
        "congress", "senate", "house", "usgov", "us_gov", "gov_us", "usa_gov", "usa",
        "police", "sheriff", "marshals", "us_marshals", "secret_service", "homeland_security",
        "department_of_justice", "justice_department", "doj", "sec", "ftc", "fcc", "cisa",
        "fema", "cdc", "fda", "nih", "usps", "federalreserve", "federal_reserve", "fed",
        "mi5", "mi6", "sis", "gchq", "met_police", "scotland_yard", "gov_uk", "govuk",
        "nhs", "hmrc", "ofcom", "fca", "bank_of_england", "parliament", "royal_family",
        "interpol", "europol", "nato", "un", "uno", "united_nations", "who", "wto", "imf",
        "worldbank", "world_bank", "eu", "european_union", "european_commission", "europa",
        "ecb", "eurojust", "frontex", "europarl", "bundesregierung", "bundestag", "bka",
        "bnd", "bfv", "polizei", "gendarmerie", "dgsi", "dgse", "elysee", "nationale",
        "carabinieri", "polizia", "guardia_di_finanza", "mossad", "shin_bet", "idf",
        "policia", "guardia_civil", "cnp", "cni", "rcmp", "csis", "asf", "asio", "asisa",
        "afp", "nzpolice", "npa", "psia", "kisa", "nso", "isro", "rbi", "sebi", "mas",
        "hkma", "sfc", "pboc", "safe", "csirc", "cert", "cert_eu", "certus",
        "home", "index", "main", "dashboard", "workspace", "workspaces", "timeline", "activity",
        "activities", "popular", "top", "latest", "recent", "all", "global", "local", "locales",
        "locale", "language", "languages", "i18n", "cdn_cgi", "robots", "sitemap", "manifest",
        "favicon", "assets_public", "public_assets", "static_assets", "media_assets",
        "storage", "bucket", "buckets", "blob", "blobs", "object", "objects", "image", "images",
        "photo", "photos", "video", "videos", "audio", "audios", "file", "attachment",
        "attachments", "export", "exports", "import", "imports", "backup", "backups",
        "restore_account", "session", "sessions", "token", "tokens", "jwt", "cookie", "cookies",
        "csrf", "xsrf", "sso", "saml", "openid", "oidc", "totp", "mfa", "2fa", "passkey",
        "passkeys", "webauthn", "credential", "credentials", "secret", "secrets", "key", "keys",
        "apikey", "api_key", "api_keys", "client", "clients", "client_id", "client_secret",
        "service", "services", "service_account", "service_accounts", "bot", "bots", "robot",
        "robots_txt", "crawler", "crawlers", "spider", "spiders", "agent", "agents", "daemon",
        "noreply", "no_reply", "donotreply", "do_not_reply", "mailer", "postmaster", "hostmaster",
        "webmaster", "sysadmin", "operator", "ops", "devops", "sre", "infra", "infrastructure",
        "network", "networks", "dns", "domain", "domains", "host", "hosts", "hosting", "server",
        "servers", "proxy", "proxies", "gateway", "gateways", "router", "routers", "cache",
        "queue", "queues", "worker", "workers", "job", "jobs_queue", "cron", "scheduler",
        "database", "databases", "db", "sql", "postgres", "postgresql", "mysql", "redis",
        "elastic", "elasticsearch", "kafka", "rabbitmq", "grpc", "rest", "graphql", "socket",
        "websocket", "ws", "rss", "atom", "xml", "json", "yaml", "yml", "well_known",
        "wellknown", "acme", "acme_challenge", "letsencrypt", "ssl", "tls", "cert", "certs",
        "certificate", "certificates", "mailing", "newsletter", "newsletters", "digest",
        "notification_center", "alerts", "alert", "incident", "incidents", "uptime",
        "monitoring", "monitor", "observability", "logs", "log", "audit", "audits", "analytics",
        "telemetry", "trace", "traces", "rate_limit", "rate_limits", "limits", "quota", "quotas",
        "flag", "flags", "feature", "features", "feature_flags", "experiment", "experiments",
        "labs", "lab", "sandbox", "canary", "nightly", "edge", "stable", "rc",
        "owner", "owners", "founder", "founders", "cofounder", "cofounders", "ceo", "cto",
        "cfo", "coo", "lead", "manager", "maintainer", "maintainers", "developer", "developers",
        "engineer", "engineers", "employee", "employees", "contractor", "contractors",
        "volunteer", "volunteers", "vip", "vips", "premium", "pro", "plus", "enterprise",
        "business", "commercial", "sales", "marketing", "ads", "ad", "advertising", "promo",
        "promotion", "promotions", "sponsor", "sponsors", "sponsored", "affiliate",
        "affiliates", "creator", "creators", "studio", "studios", "agency", "agencies",
        "press_team", "media_team", "brand_safety", "brand_protection", "legal_team",
        "privacy_team", "security_center", "trust_center", "safety_center", "moderation_team",
        "compliance", "compliance_team", "appeal", "appeals", "ticket", "tickets", "case",
        "cases", "complaint", "complaints", "feedback", "contact_us", "helpdesk_team",
        "support_center", "customer_success", "success_team", "account_manager",
        "billing_support", "payment_support", "refund", "refunds", "chargeback", "chargebacks",
        "tax", "taxes", "vat", "receipt", "receipts", "pricing", "plans", "plan", "license",
        "licenses", "subscription", "subscriptions_manage", "mailbox", "mailboxes", "calendar",
        "calendars", "drive", "browser", "browsers", "wallet", "wallets", "pay", "flora_pay",
        "flora_mail", "flora_browser", "flora_drive", "flora_music", "flora_social",
        "flora_id", "flora_account", "flora_accounts", "flora_service", "flora_services",
        "floranet", "floraapp", "floraweb", "flora_user", "flora_users", "flora_dev",
        "flora_beta", "flora_news", "flora_blog", "flora_status", "flora_help", "flora_legal",
        "flora_privacy", "flora_terms", "flora_trust", "flora_safety", "flora_moderation",
        "apple_support", "google_support", "meta_support", "facebook_support", "telegram_support",
        "youtube_support", "tiktok_support", "x_support", "twitter_support", "microsoft_support",
        "amazon_support", "paypal_support", "stripe_support", "binance_support", "coinbase_support",
        "bank", "banks", "banking", "finance", "financial", "fintech", "crypto", "bitcoin",
        "btc", "ethereum", "eth", "ton", "usdt", "usdc", "nft", "nfts", "airdrop", "airdrops",
        "giveaway", "giveaways", "lottery", "lotteries", "casino", "gambling", "bet", "bets",
        "betting", "bookmaker", "bookmakers", "loan", "loans", "credit", "credits", "debt",
        "blackmail", "extortion", "dox", "doxx", "doxxing", "swat", "swatting", "ddos", "spam_bot",
        "spam_bots", "fake", "fakes", "impersonation", "impersonator", "verification_team",
        "verify_team", "blue_badge", "badge", "badges", "checkmark", "checkmarks",
        "adult", "nsfw", "nude", "nudes", "onlyfans", "camgirl", "camgirls", "escort", "escorts",
        "suicide", "self_harm", "violence", "violent", "kill", "murder", "assassin", "assassins",
        "bomb", "bombs", "explosive", "explosives", "jihad", "jihadist", "kkk", "white_power",
        "slave", "slavery", "abduction", "kidnap", "kidnapping", "rape", "rapist",
    };

    private static readonly string[] ReservedPrefixes =
    [
        "admin",
        "administrator",
        "support",
        "helpdesk",
        "official",
        "verified",
        "moderator",
        "mod_team",
        "flora_official",
        "flora_team",
        "flora_support",
        "flora_admin",
        "flora_security",
        "security_team",
        "trust_and_safety",
        "abuse_team",
        "report_abuse",
        "staff",
        "team",
        "internal",
        "system",
        "root",
        "service_",
        "bot_",
        "noreply",
        "no_reply",
        "mailer",
        "postmaster",
        "hostmaster",
        "webmaster",
        "sysadmin",
        "operator",
        "devops",
        "infra",
        "security_",
        "trust_",
        "safety_",
        "moderation_",
        "billing_",
        "payment_",
        "legal_",
        "privacy_",
        "compliance_",
        "flora_",
        "floranet",
        "floraapp",
        "floraweb",
        "verify_",
        "verification_",
        "gosuslugi",
        "sberbank",
        "tinkoff",
        "vtb",
        "alfabank",
        "fbi",
        "cia",
        "nsa",
        "dhs",
        "dod",
        "dea",
        "atf",
        "ice",
        "cbp",
        "tsa",
        "irs",
        "treasury",
        "police",
        "sheriff",
        "interpol",
        "europol",
        "nato",
        "un",
        "who",
        "mi5",
        "mi6",
        "gchq",
        "mossad",
        "policia",
        "polizei",
        "gendarmerie",
        "gov_",
        "paypal",
        "stripe",
        "binance",
        "coinbase",
        "bank",
        "crypto",
    ];

    public static bool IsReserved(string normalizedUsername)
    {
        if (string.IsNullOrEmpty(normalizedUsername))
            return true;

        var lower = normalizedUsername.ToLowerInvariant();
        if (Exact.Contains(lower))
            return true;

        var collapsed = CollapseSeparators(lower);
        if (collapsed != lower && Exact.Contains(collapsed))
            return true;

        foreach (var prefix in ReservedPrefixes)
        {
            if (lower.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    public static string CollapseSeparators(string username) =>
        username.Replace("_", "", StringComparison.Ordinal);

    public static string NormalizeForCompare(string? raw) =>
        LatinIdentifiers.NormalizeUsername(raw);
}
