plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'social.flora.mobile'
version = '1.0.0'

android {
  namespace "expo.modules.florafrci"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  sourceSets {
    main {
      jniLibs.srcDirs = ['src/main/jniLibs']
    }
  }
}
