// <auto-generated />
using System;
using Flora.Music.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flora.Music.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20260610145536_AddMusicTrackPublishedAt")]
    partial class AddMusicTrackPublishedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flora_core")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flora.Music.Domain.MusicTrack", b =>
                {
                    b.Property<Guid>("TrackUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("track_uuid");

                    b.Property<string>("ArtistDisplay")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("artist_display");

                    b.Property<byte[]>("AudioData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("audio_data");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("CoverColorId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cover_color_id");

                    b.Property<string>("CoverContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cover_content_type");

                    b.Property<byte[]>("CoverData")
                        .HasColumnType("bytea")
                        .HasColumnName("cover_data");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("GenreId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genre_id");

                    b.Property<string>("LicenseId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_id");

                    b.Property<Guid>("OwnerUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("TrackKindId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("track_kind_id");

                    b.HasKey("TrackUuid")
                        .HasName("pk_music_tracks");

                    b.HasIndex("OwnerUserUuid", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_music_tracks_owner_created");

                    b.ToTable("music_tracks", "flora_core");
                });
#pragma warning restore 612, 618
        }
    }
}
