// <auto-generated />
using System;
using Flora.Notifications.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flora.Notifications.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260609175859_AddUserNotifications")]
    partial class AddUserNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flora_core")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flora.Notifications.Domain.UserNotification", b =>
                {
                    b.Property<Guid>("NotificationUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_uuid");

                    b.Property<Guid?>("ActorUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<Guid?>("CommentUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid?>("PostUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("post_uuid");

                    b.Property<Guid>("RecipientUserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("NotificationUuid")
                        .HasName("pk_user_notifications");

                    b.HasIndex("RecipientUserUuid", "CreatedAt")
                        .HasDatabaseName("ix_user_notifications_recipient_created");

                    b.HasIndex("RecipientUserUuid", "IsRead")
                        .HasDatabaseName("ix_user_notifications_recipient_read");

                    b.ToTable("user_notifications", "flora_core");
                });
#pragma warning restore 612, 618
        }
    }
}
